# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2fd941c338903c284893b6648ff0147e3f853b76b970a0210f67c18e6ce40baf0e242f78d9d39b8d29c70829f4b585c6156e64568c26ec04484295d79767e04

test:
  secret_key_base: 20ea97206a361c3dbe9961a7a056628d7be0160c4f72940656fe9a8aac34fbc2b7d5c4bb2f0161d92fcd9544b71b803ca61ab18fab1d2ae3bec30314640c6247

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
